# Generated by Django 4.2 on 2023-05-11 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0004_tweetreplay_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetReplay',
            new_name='TweetReply',
        ),
        migrations.RenameField(
            model_name='tweetreply',
            old_name='replay',
            new_name='reply',
        ),
    ]
